// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOTuLRlCc7em41_BWgb7resMlRZlNTVys',
    appId: '1:223925672259:web:f043d440b8309a5ef837f6',
    messagingSenderId: '223925672259',
    projectId: 'store-management-56539',
    authDomain: 'store-management-56539.firebaseapp.com',
    storageBucket: 'store-management-56539.appspot.com',
    measurementId: 'G-8H1PKKPB60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqVji-o3TZGs9Mt3QMnGCHcYyi82mOwvs',
    appId: '1:223925672259:android:d9c0df55fe3de2bdf837f6',
    messagingSenderId: '223925672259',
    projectId: 'store-management-56539',
    storageBucket: 'store-management-56539.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABAQug31anD-MnihGLog1cYTXSBysflPw',
    appId: '1:223925672259:ios:62fc3d79bd236f22f837f6',
    messagingSenderId: '223925672259',
    projectId: 'store-management-56539',
    storageBucket: 'store-management-56539.appspot.com',
    iosBundleId: 'com.example.shopManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABAQug31anD-MnihGLog1cYTXSBysflPw',
    appId: '1:223925672259:ios:62fc3d79bd236f22f837f6',
    messagingSenderId: '223925672259',
    projectId: 'store-management-56539',
    storageBucket: 'store-management-56539.appspot.com',
    iosBundleId: 'com.example.shopManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOTuLRlCc7em41_BWgb7resMlRZlNTVys',
    appId: '1:223925672259:web:4a6e1cbecbc8d24ff837f6',
    messagingSenderId: '223925672259',
    projectId: 'store-management-56539',
    authDomain: 'store-management-56539.firebaseapp.com',
    storageBucket: 'store-management-56539.appspot.com',
    measurementId: 'G-XSKSY837JJ',
  );
}
